# Generated by Django 5.1.1 on 2024-10-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_userprofile_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='postal_code',
            field=models.CharField(default='00000', max_length=10),
        ),
    ]
