# Generated by Django 5.1.1 on 2024-09-25 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='inventory.product'),
        ),
        migrations.DeleteModel(
            name='ProductIngredient',
        ),
    ]
